// Auto-generated from FMHY (github.com/fmhy/edit) — complete link scrape
export type Category =
  | "AI" | "Audio" | "Code" | "Downloads" | "Files" | "Gaming" | "Guides" | "Image" | "Internet" | "Learning" | "Linux/Mac" | "Misc" | "Mobile" | "Non-English" | "Privacy" | "Reading" | "Social" | "Storage" | "System" | "Torrenting" | "Video" | "Writing";

export interface Tool {
  name: string;
  url: string;
  category: Category;
  section: string;
}

export const CATEGORIES: Category[] = ["AI", "Audio", "Code", "Downloads", "Files", "Gaming", "Guides", "Image", "Internet", "Learning", "Linux/Mac", "Misc", "Mobile", "Non-English", "Privacy", "Reading", "Social", "Storage", "System", "Torrenting", "Video", "Writing"];

export const TOOLS: Tool[] = ([
  { n:"Qwen Studio", u:"https://chat.qwen.ai/", c:"AI", s:"Official Model Sites" },
  { n:"music streaming", u:"https://rentry.co/musicstreaming", c:"Audio", s:"Streaming Apps" },
  { n:"Auto Decode", u:"https://greasyfork.org/en/scripts/485772-fmhy-base64-auto-decoder", c:"Guides", s:"General" },
  { n:"StackOverflow", u:"https://stackoverflow.com/", c:"Code", s:"Dev Communities" },
  { n:"VirusTotal", u:"https://www.virustotal.com/gui/", c:"Downloads", s:"Software Sites" },
  { n:"Official YT Documentary Channels", u:"https://github.com/superlincoln953/Free-Official-Youtube-Content?tab=readme-ov-file#Documentaries", c:"Learning", s:"Documentaries" },
  { n:"Krokiet", u:"https://github.com/qarmin/czkawka/blob/master/krokiet/README.md", c:"Files", s:"File Tools" },
  { n:"PCGamingWiki", u:"https://www.pcgamingwiki.com/", c:"Gaming", s:"Gaming Tools" },
  { n:"PuccaNoodles' Sheet", u:"https://docs.google.com/spreadsheets/d/1-8OKuEvRR038Uno--Vi9tQRe4eFCSfQTPov7nXgiJ3w/", c:"Image", s:"Image Editing" },
  { n:"Pake", u:"https://github.com/tw93/Pake", c:"Internet", s:"Internet Tools" },
  { n:"DistroWatch", u:"https://distrowatch.com/dwres.php?resource=popularity", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Awesome List Index", u:"https://github.com/sindresorhus/awesome", c:"Misc", s:"Indexes" },
  { n:"4PDA", u:"https://4pda.to/forum/", c:"Mobile", s:"Modded APKs" },
  { n:"AdslGate", u:"https://www.adslgate.com/", c:"Non-English", s:"Arabic / العربية" },
  { n:"highly recommend", u:"https://fmhy.net/beginners-guide#adblocking", c:"Privacy", s:"Adblocking" },
  { n:"Open Slum", u:"https://open-slum.org/", c:"Reading", s:"Ebooks" },
  { n:"Farside", u:"https://farside.link/", c:"Social", s:"Social Media Tools" },
  { n:"Mockoops", u:"https://mockoops.mohitya.dev/", c:"Storage", s:"App / Site Mockups" },
  { n:"Awesome Windows 11", u:"https://github.com/awesome-windows11/windows11", c:"System", s:"System Tools" },
  { n:"SortMyList", u:"https://sortmylist.com/", c:"Writing", s:"Text Tools" },
  { n:"Rules", u:"https://rutracker.org/forum/viewtopic.php?t=1045", c:"Torrenting", s:"Torrent Sites" },
  { n:"Digital Video Intro", u:"https://github.com/leandromoreira/digital_video_introduction", c:"Video", s:"Video Tools" },
  { n:"DeepSeek", u:"https://chat.deepseek.com/", c:"AI", s:"Official Model Sites" },
  { n:"Pear Desktop", u:"https://github.com/pear-devs/pear-desktop", c:"Audio", s:"Streaming Apps" },
  { n:"Cineby", u:"https://cineby.at/", c:"Guides", s:"General" },
  { n:"XDA", u:"https://xdaforums.com/", c:"Code", s:"Dev Communities" },
  { n:"Adobe Alternatives", u:"https://github.com/KenneyNL/Adobe-Alternatives", c:"Downloads", s:"Software Sites" },
  { n:"IHaveNoTV", u:"https://ihavenotv.com", c:"Learning", s:"Documentaries" },
  { n:"UnLock IT", u:"https://emcosoftware.com/unlock-it/download", c:"Files", s:"File Tools" },
  { n:"Library of Codexes", u:"https://libraryofcodexes.com/", c:"Gaming", s:"Gaming Tools" },
  { n:"Croppola", u:"https://croppola.com/", c:"Image", s:"Image Editing" },
  { n:"deploy-your-own-saas", u:"https://github.com/Atarity/deploy-your-own-saas", c:"Internet", s:"Internet Tools" },
  { n:"ArchWiki", u:"https://wiki.archlinux.org/", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Lists", u:"https://github.com/jnv/lists", c:"Misc", s:"Indexes" },
  { n:"RockMods", u:"https://www.rockmods.net/", c:"Mobile", s:"Modded APKs" },
  { n:"ZeroTaxJobs", u:"https://zerotaxjobs.com/", c:"Non-English", s:"Arabic / العربية" },
  { n:"AdGuard", u:"https://github.com/AdguardTeam/AdguardBrowserExtension", c:"Privacy", s:"Adblocking" },
  { n:"Mirrors", u:"https://en.wikipedia.org/wiki/Anna's_Archive", c:"Reading", s:"Ebooks" },
  { n:"GitLab", u:"https://gitlab.futo.org/videostreaming/grayjay", c:"Social", s:"Social Media Tools" },
  { n:"Really Good Emails", u:"https://reallygoodemails.com/", c:"Storage", s:"App / Site Mockups" },
  { n:"PC-Optimization-Hub", u:"https://github.com/BoringBoredom/PC-Optimization-Hub", c:"System", s:"System Tools" },
  { n:"OpenPaper", u:"https://openpaper.work/en/", c:"Writing", s:"Text Tools" },
  { n:"m0nkrus", u:"https://rentry.co/FMHYB64#m0nkrus", c:"Torrenting", s:"Torrent Sites" },
  { n:"Kast", u:"https://kast.gg/", c:"Video", s:"Video Tools" },
  { n:"Z.ai", u:"https://chat.z.ai/", c:"AI", s:"Official Model Sites" },
  { n:"BeatBoss", u:"https://beatboss.thevolecitor.qzz.io/", c:"Audio", s:"Streaming Apps" },
  { n:"ExT.to", u:"https://ext.to/browse/?cat=1", c:"Guides", s:"General" },
  { n:"Spiceworks Community", u:"https://community.spiceworks.com/", c:"Code", s:"Dev Communities" },
  { n:"Keyflame", u:"https://rentry.co/FMHYB64#keyflame", c:"Downloads", s:"Software Sites" },
  { n:"DocumentaryArea", u:"https://www.documentaryarea.com/", c:"Learning", s:"Documentaries" },
  { n:"Icaros", u:"https://github.com/Xanashi/Icaros", c:"Files", s:"File Tools" },
  { n:"IsItCracked", u:"https://isitcracked.com/", c:"Gaming", s:"Gaming Tools" },
  { n:"PixelFrame", u:"https://pixelframe.design/", c:"Image", s:"Image Editing" },
  { n:"Namechk", u:"https://namechk.com/", c:"Internet", s:"Internet Tools" },
  { n:"Gentoo Wiki", u:"https://wiki.gentoo.org/wiki/Main_Page", c:"Linux/Mac", s:"Linux Guides" },
  { n:"FMHY Search", u:"https://fmhy.net/posts/search", c:"Misc", s:"Indexes" },
  { n:"PlatinMods", u:"https://platinmods.com/", c:"Mobile", s:"Modded APKs" },
  { n:"arabic-reddit-extension", u:"https://github.com/andronasef/arabic-reddit-extension", c:"Non-English", s:"Arabic / العربية" },
  { n:"uAssets", u:"https://github.com/uBlockOrigin/uAssets/issues", c:"Privacy", s:"Adblocking" },
  { n:"Z-Library", u:"https://z-lib.gd/", c:"Reading", s:"Ebooks" },
  { n:"SocialBlade", u:"https://socialblade.com/", c:"Social", s:"Social Media Tools" },
  { n:"Screen from Traction", u:"https://screen.traction.one/", c:"Storage", s:"App / Site Mockups" },
  { n:"PowerToys", u:"https://learn.microsoft.com/en-us/windows/powertoys/", c:"System", s:"System Tools" },
  { n:"SmartDoc", u:"https://killytoronto.github.io/textanalyzer/", c:"Writing", s:"Text Tools" },
  { n:"Block Telemetry", u:"https://rentry.co/FMHYB64#a-dove-is-dumb", c:"Torrenting", s:"Torrent Sites" },
  { n:"Deep-Live-Cam", u:"https://github.com/hacksider/Deep-Live-Cam", c:"Video", s:"Video Tools" },
  { n:"Google AI Studio", u:"https://aistudio.google.com/app/prompts/new_chat", c:"AI", s:"Official Model Sites" },
  { n:"PlayTorrio", u:"https://playtorrio.xyz/", c:"Audio", s:"Streaming Apps" },
  { n:"Streamed", u:"https://streamed.pk/", c:"Guides", s:"General" },
  { n:"DEV Community", u:"https://dev.to/", c:"Code", s:"Dev Communities" },
  { n:"Software CSE", u:"https://cse.google.com/cse?cx=ae17d0c72fa6cbcd4", c:"Downloads", s:"Software Sites" },
  { n:"Documentary", u:"https://www.docplus.com/", c:"Learning", s:"Documentaries" },
  { n:"HTTPDirfs", u:"https://github.com/fangfufu/httpdirfs", c:"Files", s:"File Tools" },
  { n:"HowLongToBeat", u:"https://howlongtobeat.com/", c:"Gaming", s:"Gaming Tools" },
  { n:"Scribus", u:"https://www.scribus.net/", c:"Image", s:"Image Editing" },
  { n:"byp4xx", u:"https://github.com/lobuhi/byp4xx", c:"Internet", s:"Internet Tools" },
  { n:"Debian Wiki", u:"https://wiki.debian.org/", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Awesome Search", u:"https://awesomelists.top/", c:"Misc", s:"Indexes" },
  { n:"PDALife", u:"https://pdalife.com/", c:"Mobile", s:"Modded APKs" },
  { n:"Stardima", u:"https://www.stardima.com/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"SponsorBlock", u:"https://sponsor.ajay.app/", c:"Privacy", s:"Adblocking" },
  { n:"Mobilism", u:"https://forum.mobilism.org", c:"Reading", s:"Ebooks" },
  { n:"LiveCounts", u:"https://livecounts.io/", c:"Social", s:"Social Media Tools" },
  { n:"Awesome CSS Frameworks", u:"https://github.com/troxler/awesome-css-frameworks", c:"Storage", s:"CSS Framework Tools" },
  { n:"Sysinternals", u:"https://learn.microsoft.com/en-us/sysinternals/", c:"System", s:"System Tools" },
  { n:"Diffr", u:"https://loilo.github.io/diffr/", c:"Writing", s:"Text Tools" },
  { n:"1337x", u:"https://1337x.to/home/", c:"Torrenting", s:"Torrent Sites" },
  { n:"VideoHelp Forum", u:"https://forum.videohelp.com/", c:"Video", s:"Video Tools" },
  { n:"Gemini", u:"https://gemini.google.com/", c:"AI", s:"Official Model Sites" },
  { n:"yewtube", u:"https://github.com/mps-youtube/yewtube", c:"Audio", s:"Streaming Apps" },
  { n:"GoPlay", u:"https://goplay.su/", c:"Guides", s:"General" },
  { n:"Blind", u:"https://www.teamblind.com/", c:"Code", s:"Dev Communities" },
  { n:"CracksURL", u:"https://cracksurl.com/", c:"Downloads", s:"Software Sites" },
  { n:"1337x Documentaries", u:"https://1337x.to/top-100-documentaries", c:"Learning", s:"Documentaries" },
  { n:"WinBtrfs", u:"https://github.com/maharmstone/btrfs", c:"Files", s:"File Tools" },
  { n:"Game Pauser", u:"https://madebyjase.com/game-pauser/", c:"Gaming", s:"Gaming Tools" },
  { n:"Images.weserv.nl", u:"https://images.weserv.nl/", c:"Image", s:"Image Editing" },
  { n:"fast", u:"https://fast.com/", c:"Internet", s:"Network Tools" },
  { n:"Linux Journey", u:"https://labex.io/linuxjourney", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Couleur Tweak Tips", u:"https://ctt.cx/", c:"Misc", s:"Indexes" },
  { n:"AN1", u:"https://an1.com/", c:"Mobile", s:"Modded APKs" },
  { n:"My Cima", u:"https://my-cima.video/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"Bookmarklet", u:"https://github.com/mchangrh/sb.js", c:"Privacy", s:"Adblocking" },
  { n:"Bookracy", u:"https://bookracy.com/", c:"Reading", s:"Ebooks" },
  { n:"LibRedirect", u:"https://github.com/libredirect/browser_extension", c:"Social", s:"Social Media Tools" },
  { n:"Classless CSS", u:"https://github.com/dbohdan/classless-css", c:"Storage", s:"CSS Framework Tools" },
  { n:"SuperF4", u:"https://stefansundin.github.io/superf4/", c:"System", s:"System Tools" },
  { n:"Count Duplicates", u:"https://www.somacon.com/p568.php", c:"Writing", s:"Text Tools" },
  { n:"IMDb Ratings", u:"https://github.com/kotylo/1337imdb", c:"Torrenting", s:"Torrent Sites" },
  { n:"ICAT", u:"https://www.nvidia.com/en-us/geforce/technologies/icat/", c:"Video", s:"Video Tools" },
  { n:"Meta AI", u:"https://www.meta.ai/", c:"AI", s:"Official Model Sites" },
  { n:"WAVE", u:"https://waveapp.pages.dev/", c:"Audio", s:"Streaming Apps" },
  { n:"Simkl", u:"https://simkl.com/", c:"Guides", s:"General" },
  { n:"IndieHackers", u:"https://www.indiehackers.com/", c:"Code", s:"Dev Communities" },
  { n:"LRepacks", u:"https://lrepacks.net/", c:"Downloads", s:"Software Sites" },
  { n:"YT Video Essay Hall of Fame", u:"https://docs.google.com/spreadsheets/d/1pMlfjJ4gb0vMt2xrQITBMzWypNHMj-lWKkK1KC6EjxA/edit?gid=88681539", c:"Learning", s:"Documentaries" },
  { n:"mergerfs", u:"https://github.com/trapexit/mergerfs", c:"Files", s:"File Tools" },
  { n:"Valve Archive", u:"https://valvearchive.com/", c:"Gaming", s:"Gaming Tools" },
  { n:"GradientArt", u:"https://gra.dient.art/", c:"Image", s:"Image Editing" },
  { n:"Safing Portmaster", u:"https://safing.io/", c:"Internet", s:"Network Tools" },
  { n:"HowToLinux", u:"https://howtolinux.vercel.app", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Track Awesome List", u:"https://www.trackawesomelist.com/", c:"Misc", s:"Indexes" },
  { n:"Android APK CSE", u:"https://cse.google.com/cse?cx=e0d1769ccf74236e8", c:"Mobile", s:"Modded APKs" },
  { n:"egydead", u:"https://egydead.skin/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"Disblock Origin", u:"https://codeberg.org/AllPurposeMat/Disblock-Origin", c:"Privacy", s:"Adblocking" },
  { n:"MyAnonaMouse", u:"https://www.myanonamouse.net/", c:"Reading", s:"Ebooks" },
  { n:"Numblr", u:"https://github.com/heyLu/numblr", c:"Social", s:"Social Media Tools" },
  { n:"Awesome TailwindCSS", u:"https://github.com/aniftyco/awesome-tailwindcss", c:"Storage", s:"CSS Framework Tools" },
  { n:"CPU-Z", u:"https://www.cpuid.com/softwares/cpu-z.html", c:"System", s:"System Tools" },
  { n:"WindowTextExtractor", u:"https://github.com/AlexanderPro/WindowTextExtractor", c:"Writing", s:"Text Tools" },
  { n:"RARBG Dump", u:"https://rarbgdump.com/", c:"Torrenting", s:"Torrent Sites" },
  { n:"videoduplicatefinder", u:"https://github.com/0x90d/videoduplicatefinder", c:"Video", s:"Video Tools" },
  { n:"Kimi", u:"https://www.kimi.com/", c:"AI", s:"Official Model Sites" },
  { n:"pulse", u:"https://473999.net/pulse", c:"Audio", s:"Streaming Apps" },
  { n:"Miruro", u:"https://www.miruro.com/", c:"Guides", s:"General" },
  { n:"CyberArsenal", u:"https://cyberarsenal.org/", c:"Code", s:"Dev Communities" },
  { n:"Soft98", u:"https://soft98.ir/", c:"Downloads", s:"Software Sites" },
  { n:"LearnOutLoud", u:"https://www.learnoutloud.com/", c:"Learning", s:"Documentaries" },
  { n:"ExampleFile", u:"https://www.examplefile.com/", c:"Files", s:"File Tools" },
  { n:"Sunshine", u:"https://app.lizardbyte.dev/Sunshine/", c:"Gaming", s:"Gaming Tools" },
  { n:"Canvas", u:"https://www.nvidia.com/en-us/studio/creative-side-hustle/", c:"Image", s:"Image Editing" },
  { n:"Pinging", u:"https://www.pinging.net/", c:"Internet", s:"Network Tools" },
  { n:"Sindresorhus Guides", u:"https://github.com/sindresorhus/guides", c:"Linux/Mac", s:"Linux Guides" },
  { n:"ForumDirectory", u:"https://www.forumdirectory.com/", c:"Misc", s:"Indexes" },
  { n:"APKVision", u:"https://apkvision.org/", c:"Mobile", s:"Modded APKs" },
  { n:"FilmCity", u:"https://m.filmcity12.com/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"Popup Blocker (strict", u:"https://github.com/schomery/popup-blocker", c:"Privacy", s:"Adblocking" },
  { n:"Library Genesis", u:"https://libgen.li/", c:"Reading", s:"Ebooks" },
  { n:"Pinless", u:"https://pinterest.bunk.im/", c:"Social", s:"Social Media Tools" },
  { n:"Tailwind CSS", u:"https://tailwindcss.com/", c:"Storage", s:"CSS Framework Tools" },
  { n:"Bulk Crap Uninstaller", u:"https://www.bcuninstaller.com/", c:"System", s:"System Tools" },
  { n:"Unredact", u:"https://github.com/leedrake5/unredact", c:"Writing", s:"Text Tools" },
  { n:"LimeTorrents", u:"https://www.limetorrents.fun/", c:"Torrenting", s:"Torrent Sites" },
  { n:"MkvDefaultTrackChanger", u:"https://mkvdefaulttrackchanger.pages.dev/", c:"Video", s:"Video Tools" },
  { n:"ChatGPT", u:"https://chatgpt.com/", c:"AI", s:"Official Model Sites" },
  { n:"BetterSoundcloud", u:"https://alirezakj.com/bsc/", c:"Audio", s:"Streaming Apps" },
  { n:"Tokyo Insider", u:"https://www.tokyoinsider.com/", c:"Guides", s:"General" },
  { n:"Tech-Blogs", u:"https://tech-blogs.dev/", c:"Code", s:"Dev Communities" },
  { n:"Mobilism", u:"https://forum.mobilism.org/", c:"Downloads", s:"Software Sites" },
  { n:"Top Documentary Films", u:"https://topdocumentaryfilms.com/", c:"Learning", s:"Documentaries" },
  { n:"Firefox", u:"https://addons.mozilla.org/firefox/addon/ab-download-manager/", c:"Files", s:"Download Managers" },
  { n:"Moonlight", u:"https://moonlight-stream.org/", c:"Gaming", s:"Gaming Tools" },
  { n:"Image Splitter", u:"https://ruyili.ca/image-splitter/", c:"Image", s:"Image Editing" },
  { n:"NetBlocks", u:"https://api.webprobe.org/", c:"Internet", s:"Network Tools" },
  { n:"Erik Dubois", u:"https://www.youtube.com/c/ErikDubois", c:"Linux/Mac", s:"Linux Guides" },
  { n:"theindex.fyi", u:"https://theindex.fyi/", c:"Misc", s:"Indexes" },
  { n:"LiteAPKs", u:"https://liteapks.com/", c:"Mobile", s:"Modded APKs" },
  { n:"TopCinema", u:"https://web6.topcinema.cam/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"BehindTheOverlay", u:"https://github.com/NicolaeNMV/BehindTheOverlay", c:"Privacy", s:"Adblocking" },
  { n:"Reading CSE", u:"https://cse.google.com/cse?cx=006516753008110874046:s9ddesylrm8", c:"Reading", s:"Ebooks" },
  { n:"StoryLooker", u:"https://storylooker.com/", c:"Social", s:"Social Media Tools" },
  { n:"daisyUI", u:"https://daisyui.com/", c:"Storage", s:"CSS Framework Tools" },
  { n:"NanaRun", u:"https://github.com/M2Team/NanaRun", c:"System", s:"System Tools" },
  { n:"Textify", u:"https://ramensoftware.com/textify", c:"Writing", s:"Text Tools" },
  { n:"rutor.info", u:"https://rutor.is/", c:"Torrenting", s:"Torrent Sites" },
  { n:"MP4Recover", u:"https://github.com/ActiveTK/MP4Recover", c:"Video", s:"Video Tools" },
  { n:"LongCat", u:"https://longcat.chat/", c:"AI", s:"Official Model Sites" },
  { n:"Nuclear", u:"https://nuclearplayer.com/", c:"Audio", s:"Streaming Apps" },
  { n:"Nyaa", u:"https://nyaa.si/", c:"Guides", s:"General" },
  { n:"The Devs Network", u:"https://thedevs.network/", c:"Code", s:"Dev Communities" },
  { n:"Nsane Forums", u:"https://www.nsaneforums.com/", c:"Downloads", s:"Software Sites" },
  { n:"Thought Maybe", u:"https://thoughtmaybe.com/", c:"Learning", s:"Documentaries" },
  { n:"JDownloader", u:"https://jdownloader.org/", c:"Files", s:"Download Managers" },
  { n:"Greenlight", u:"https://github.com/unknownskl/greenlight", c:"Gaming", s:"Gaming Tools" },
  { n:"PicFont", u:"https://picfont.com/", c:"Image", s:"Image Editing" },
  { n:"WiFi Analyzer", u:"https://apps.microsoft.com/store/detail/wifi-analyzer/9NBLGGH33N0N", c:"Internet", s:"Network Tools" },
  { n:"Linuxtopia", u:"https://www.linuxtopia.org/", c:"Linux/Mac", s:"Linux Guides" },
  { n:"Dan's Guides", u:"https://rentry.co/danxyz7", c:"Misc", s:"Indexes" },
  { n:"Modyolo", u:"https://modyolo.com/", c:"Mobile", s:"Modded APKs" },
  { n:"Anime3rb", u:"https://anime3rb.com/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"BilibiliSponsorBlock", u:"https://www.bsbsb.top/", c:"Privacy", s:"Adblocking" },
  { n:"Internet Archive", u:"https://archive.org/details/texts", c:"Reading", s:"Ebooks" },
  { n:"grapper", u:"https://grapper.gab.net.eu.org/", c:"Social", s:"Social Media Tools" },
  { n:"TailBlocks", u:"https://tailblocks.cc/", c:"Storage", s:"CSS Framework Tools" },
  { n:"BleachBit", u:"https://www.bleachbit.org/", c:"System", s:"System Tools" },
  { n:"Scanner", u:"https://simon-knuth.github.io/scanner/index", c:"Writing", s:"Text Tools" },
  { n:"Torrenting", u:"https://www.torrenting.com/", c:"Torrenting", s:"Torrent Sites" },
  { n:"VHS Decode", u:"https://github.com/oyvindln/vhs-decode", c:"Video", s:"Video Tools" },
  { n:"MiMo Studio", u:"https://aistudio.xiaomimimo.com/", c:"AI", s:"Official Model Sites" },
  { n:"FunkWhale", u:"https://funkwhale.audio/", c:"Audio", s:"Streaming Apps" },
  { n:"MAL", u:"https://myanimelist.net/", c:"Guides", s:"General" },
  { n:"KrebsOnSecurity", u:"https://krebsonsecurity.com/", c:"Code", s:"Dev News" },
  { n:"AlternativeTo", u:"https://alternativeto.net/", c:"Downloads", s:"Software Sites" },
  { n:"Media Burn Archive", u:"https://mediaburn.org/", c:"Learning", s:"Documentaries" },
  { n:"Debloat Guide", u:"https://clarasguide.valeena.workers.dev/Guides/jdownloader2/", c:"Files", s:"Download Managers" },
  { n:"Better xCloud", u:"https://better-xcloud.github.io/", c:"Gaming", s:"Gaming Tools" },
  { n:"GIMP", u:"https://www.gimp.org/", c:"Image", s:"Editing Software" },
  { n:"Wireshark", u:"https://www.wireshark.org/", c:"Internet", s:"Network Tools" },
  { n:"Linux Roadmap", u:"https://roadmap.sh/linux", c:"Linux/Mac", s:"Linux Guides" },
  { n:"xRanks", u:"https://xranks.com/", c:"Misc", s:"Indexes" },
  { n:"LeeAPK", u:"https://leeapk.com/", c:"Mobile", s:"Modded APKs" },
  { n:"nghmat", u:"https://songs.nghmat.com/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"FilterLists", u:"https://filterlists.com/", c:"Privacy", s:"Adblock Filters" },
  { n:"WeLib", u:"https://welib.org/", c:"Reading", s:"Ebooks" },
  { n:"Social-Searcher", u:"https://www.social-searcher.com/", c:"Social", s:"Social Media Tools" },
  { n:"Terminal CSS", u:"https://terminalcss.xyz/", c:"Storage", s:"CSS Framework Tools" },
  { n:"PolicyPlus", u:"https://github.com/Fleex255/PolicyPlus", c:"System", s:"System Tools" },
  { n:"Text to Handwriting", u:"https://saurabhdaware.github.io/text-to-handwriting/", c:"Writing", s:"Text Tools" },
  { n:"ExT", u:"https://ext.to/", c:"Torrenting", s:"Aggregators" },
  { n:"VidClue", u:"https://vidclue.com/", c:"Video", s:"Video Tools" },
  { n:"Grok", u:"https://grok.com/", c:"AI", s:"Official Model Sites" },
  { n:"Muffon", u:"https://muffon.netlify.app/", c:"Audio", s:"Streaming Apps" },
  { n:"ArchiveTune", u:"https://archivetune.koiiverse.cloud/", c:"Guides", s:"General" },
  { n:"Lobsters", u:"https://lobste.rs/", c:"Code", s:"Dev News" },
  { n:"AIOWares", u:"https://www.aiowares.com/", c:"Downloads", s:"Software Sites" },
  { n:"ARTE", u:"https://www.arte.tv/", c:"Learning", s:"Documentaries" },
  { n:"IDM", u:"https://rentry.co/FMHYB64#idm", c:"Files", s:"Download Managers" },
  { n:"Ghost Hunter Pro", u:"https://github.com/MarchTheDev/GhostHunterPro", c:"Gaming", s:"Gaming Tools" },
  { n:"ImageMagick", u:"https://imagemagick.org/", c:"Image", s:"Editing Software" },
  { n:"Trippy", u:"https://trippy.cli.rs/", c:"Internet", s:"Network Tools" },
  { n:"Vim Tutorials", u:"https://www.youtube.com/playlist?list=PL3cu45aM3C2DJVGfCjSBB1yD9YkC7q27-", c:"Linux/Mac", s:"Linux Guides" },
  { n:"findPWA", u:"https://findpwa.com/", c:"Misc", s:"Indexes" },
  { n:"Nsane Forums", u:"https://nsaneforums.com/", c:"Mobile", s:"Modded APKs" },
  { n:"ArabicFonts", u:"https://arabicfonts.net/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"LegitimateURLShortener", u:"https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/LegitimateURLShortener.txt", c:"Privacy", s:"Adblock Filters" },
  { n:"Liber3", u:"https://liber3.eth.limo/", c:"Reading", s:"Ebooks" },
  { n:"Social Media Hacker List", u:"https://github.com/MobileFirstLLC/social-media-hacker-list", c:"Social", s:"Social Media Tools" },
  { n:"RAWGraphs", u:"https://app.rawgraphs.io/", c:"Storage", s:"Data Visualization Tools" },
  { n:"GhostBuster", u:"https://bitbucket.org/wvd-vegt/ghostbuster/src/master/", c:"System", s:"System Tools" },
  { n:"DocuSeal", u:"https://www.docuseal.com/", c:"Writing", s:"Text Tools" },
  { n:"Knaben", u:"https://knaben.org/", c:"Torrenting", s:"Aggregators" },
  { n:"ImgBurn", u:"https://www.majorgeeks.com/files/details/imgburn.html", c:"Video", s:"Disc Utilities" },
  { n:"Microsoft Copilot", u:"https://copilot.microsoft.com", c:"AI", s:"Official Model Sites" },
  { n:"Sonosano", u:"https://github.com/KRSHH/Sonosano", c:"Audio", s:"Streaming Apps" },
  { n:"SpotC", u:"https://spotc.yodaluca.dev/", c:"Guides", s:"General" },
  { n:"DevURLs", u:"https://devurls.com/", c:"Code", s:"Dev News" },
  { n:"DownloadHa", u:"https://www.downloadha.com/", c:"Downloads", s:"Software Sites" },
  { n:"Documentary Network", u:"https://documentary.net/", c:"Learning", s:"Documentaries" },
  { n:"Go Speed", u:"https://gopeed.com/", c:"Files", s:"Download Managers" },
  { n:"Arcade Database", u:"https://zenius-i-vanisher.com/v5.2/arcades.php", c:"Gaming", s:"Gaming Tools" },
  { n:"Affinity", u:"https://www.affinity.studio/", c:"Image", s:"Editing Software" },
  { n:"NETworkManager", u:"https://borntoberoot.net/NETworkManager/", c:"Internet", s:"Network Tools" },
  { n:"Boot-Repair", u:"https://help.ubuntu.com/community/Boot-Repair", c:"Linux/Mac", s:"Linux Guides" },
  { n:"SmartLinks", u:"https://smartlinks.org/index.html", c:"Misc", s:"Indexes" },
  { n:"Sbenny", u:"https://sbenny.com/", c:"Mobile", s:"Modded APKs" },
  { n:"Eternal Dream Arabization", u:"https://www.etrdream.com/", c:"Non-English", s:"Downloading / تحميل" },
  { n:"Hagezi Blocklists", u:"https://github.com/hagezi/dns-blocklists", c:"Privacy", s:"Adblock Filters" },
  { n:"BookSee", u:"https://en.booksee.org/", c:"Reading", s:"Ebooks" },
  { n:"ExportComments", u:"https://exportcomments.com/", c:"Social", s:"Social Media Tools" },
  { n:"draw.io", u:"https://www.drawio.com/", c:"Storage", s:"Data Visualization Tools" },
  { n:"Should I Remove It", u:"https://www.shouldiremoveit.com/", c:"System", s:"System Tools" },
  { n:"TemplateLab", u:"https://templatelab.com/", c:"Writing", s:"Text Tools" },
  { n:"TorrentProject", u:"https://torrentproject.cc/", c:"Torrenting", s:"Aggregators" },
  { n:"VidCoder", u:"https://vidcoder.net/", c:"Video", s:"Disc Utilities" },
  { n:"Claude", u:"https://claude.ai/", c:"AI", s:"Official Model Sites" },
  { n:"YouTube Music", u:"https://music.youtube.com/", c:"Audio", s:"Streaming Sites" },
  { n:"HizSearch", u:"https://hizsearch.pages.dev/", c:"Guides", s:"General" },
  { n:"daily.dev", u:"https://app.daily.dev/posts", c:"Code", s:"Dev News" },
  { n:"Moum", u:"https://moum.top/en/", c:"Downloads", s:"Software Sites" },
  { n:"Documentary Storm", u:"https://www.documentarystorm.com/", c:"Learning", s:"Documentaries" },
  { n:"Motrix Next", u:"https://motrix-next.pages.dev/", c:"Files", s:"Download Managers" },
  { n:"TASVideos", u:"https://tasvideos.org/", c:"Gaming", s:"Gaming Tools" },
  { n:"LazPaint", u:"https://lazpaint.github.io/", c:"Image", s:"Editing Software" },
  { n:"mRemoteNG", u:"https://mremoteng.org/", c:"Internet", s:"Network Tools" },
  { n:"Wikiman", u:"https://github.com/filiparag/wikiman", c:"Linux/Mac", s:"Linux Guides" },
  { n:"OneMillionScreenshots", u:"https://onemillionscreenshots.com/", c:"Misc", s:"Indexes" },
  { n:"APKSum", u:"https://www.apksum.com/", c:"Mobile", s:"Modded APKs" },
  { n:"ArabP2P", u:"https://www.arabp2p.net/", c:"Non-English", s:"Torrenting / التورنت" },
  { n:"blacklist", u:"https://github.com/anudeepND/blacklist", c:"Privacy", s:"Adblock Filters" },
  { n:"BDeBooks", u:"https://bdebooks.com/en/", c:"Reading", s:"Ebooks" },
  { n:"socid_extractor", u:"https://github.com/soxoj/socid-extractor", c:"Social", s:"Social Media Tools" },
  { n:"Kroki", u:"https://kroki.io/#try", c:"Storage", s:"Data Visualization Tools" },
  { n:"CoreTemp", u:"https://www.alcpu.com/CoreTemp/", c:"System", s:"System Tools" },
  { n:"Asciify", u:"https://asciify.dev/", c:"Writing", s:"Text Tools" },
  { n:"DaMagNet", u:"https://damag.net/", c:"Torrenting", s:"Aggregators" },
  { n:"MakeMKV", u:"https://www.makemkv.com/", c:"Video", s:"Disc Utilities" },
  { n:"MiniMax AI", u:"https://agent.minimax.io/", c:"AI", s:"Official Model Sites" },
  { n:"Monochrome", u:"https://monochrome.tf/", c:"Audio", s:"Streaming Sites" },
  { n:"Emulation Wiki", u:"https://emulation.gametechwiki.com/index.php/Main_Page", c:"Guides", s:"General" },
  { n:"This Week in Rust", u:"https://this-week-in-rust.org/", c:"Code", s:"Dev News" },
  { n:"RetroSystemRevival", u:"https://retrosystemsrevival.blogspot.com/", c:"Downloads", s:"Software Sites" },
  { n:"Rocumentaries", u:"https://rocumentaries.com/", c:"Learning", s:"Documentaries" },
  { n:"FDM", u:"https://www.freedownloadmanager.org/", c:"Files", s:"Download Managers" },
  { n:"VGHF Digital Archive", u:"https://library.gamehistory.org/", c:"Gaming", s:"Gaming Tools" },
  { n:"PhotoDemon", u:"https://photodemon.org/", c:"Image", s:"Editing Software" },
  { n:"MyPublicWiFi", u:"https://www.mypublicwifi.com/", c:"Internet", s:"Network Tools" },
  { n:"Linux Command Library", u:"https://linuxcommandlibrary.com/", c:"Linux/Mac", s:"CLI Cheat Sheets" },
  { n:"Data Hoarding", u:"https://datahoarding.org/", c:"Misc", s:"Indexes" },
  { n:"Android Zone", u:"https://android-zone.ws/", c:"Mobile", s:"Modded APKs" },
  { n:"FaselHD", u:"https://web52518x.faselhdx.bid/", c:"Non-English", s:"Streaming / البث" },
] as const).map((x: any) => ({ name: x.n, url: x.u, category: x.c, section: x.s })) as Tool[];
